# Generated by Django 6.0.2 on 2026-02-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/pictures/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='profiles/logos/')),
                ('subscription_type', models.CharField(choices=[('individual', 'Individual Cards'), ('sm_business', 'S&M Business'), ('enterprise', 'Enterprise'), ('corporate', 'Corporate')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='checkout.checkoutsubmission')),
            ],
            options={
                'unique_together': {('submission', 'platform')},
            },
        ),
    ]
