# Generated by Django 6.0.2 on 2026-02-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_cardpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpricing',
            name='plan_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
